--bk001 로그인
--고객 테이블 생성
CREATE TABLE CUST
(
    CUST_NO    	CHAR(10) NOT NULL,
    CUST_NM    	VARCHAR2(30) NOT NULL,
    ZIPCD    	CHAR(5) NOT NULL,
    RDNM_ADDR	VARCHAR2(100) NOT NULL,
    DTL_ADDR    VARCHAR2(100) NOT NULL
);

ALTER TABLE CUST
 ADD CONSTRAINT CUST_PK PRIMARY KEY ( CUST_NO );

COMMENT ON COLUMN CUST.CUST_NO IS '고객번호';

COMMENT ON COLUMN CUST.CUST_NM IS '고객명';

COMMENT ON COLUMN CUST.ZIPCD IS '우편번호';

COMMENT ON COLUMN CUST.RDNM_ADDR IS '도로명주소';

COMMENT ON COLUMN CUST.DTL_ADDR IS '상세주소';

COMMENT ON TABLE CUST IS '고객';

desc cust;

CREATE TABLE PBCM
(
    PBCM_CD    CHAR(4) NOT NULL,
    PBCM_NM    VARCHAR2(50) NOT NULL,
    CHPR_NM    VARCHAR2(30) NOT NULL,
    CHPR_TELNO    VARCHAR2(11) NOT NULL
);

COMMENT ON COLUMN PBCM.PBCM_CD IS '출판사코드';

COMMENT ON COLUMN PBCM.PBCM_NM IS '출판사명';

COMMENT ON COLUMN PBCM.CHPR_NM IS '담당자명';

COMMENT ON COLUMN PBCM.CHPR_TELNO IS '담당자전화번호';

COMMENT ON TABLE PBCM IS '출판사';

CREATE UNIQUE INDEX PBCM_PK ON PBCM
( PBCM_CD );

ALTER TABLE PBCM
 ADD CONSTRAINT PBCM_PK PRIMARY KEY ( PBCM_CD );

desc pbcm;

CREATE TABLE BOOK
(
    BK_NO    CHAR(10) NOT NULL,
    BK_NM    VARCHAR2(50) NOT NULL,
    BK_UPRC    NUMBER(9) NOT NULL,
    PBCM_CD    CHAR(4) NOT NULL
);

COMMENT ON COLUMN BOOK.BK_NO IS '도서번호';

COMMENT ON COLUMN BOOK.BK_NM IS '도서명';

COMMENT ON COLUMN BOOK.BK_UPRC IS '도서단가';

COMMENT ON COLUMN BOOK.PBCM_CD IS '출판사코드';

COMMENT ON TABLE BOOK IS '도서';

CREATE UNIQUE INDEX BOOK_PK ON BOOK
( BK_NO );

ALTER TABLE BOOK
 ADD CONSTRAINT BOOK_PK PRIMARY KEY ( BK_NO );

ALTER TABLE BOOK
 ADD CONSTRAINT BOOK_FK FOREIGN KEY ( PBCM_CD )
 REFERENCES PBCM (PBCM_CD );
 
 desc book;

CREATE TABLE ORD_MST
(
    ORD_NO    CHAR(10) NOT NULL,
    CUST_NO    CHAR(10) NOT NULL,
    ORD_DT    CHAR(10) NOT NULL,
    TOT_CNT    NUMBER(9) DEFAULT 0 NOT NULL,
    TOT_AMT    NUMBER(11) DEFAULT 0 NOT NULL
);

COMMENT ON COLUMN ORD_MST.ORD_NO IS '주문번호';

COMMENT ON COLUMN ORD_MST.CUST_NO IS '고객번호';

COMMENT ON COLUMN ORD_MST.ORD_DT IS '주문일자';

COMMENT ON COLUMN ORD_MST.TOT_CNT IS '총건수';

COMMENT ON COLUMN ORD_MST.TOT_AMT IS '총금액';

COMMENT ON TABLE ORD_MST IS '주문정보';

CREATE UNIQUE INDEX ORD_MST_PK ON ORD_MST
( ORD_NO );

ALTER TABLE ORD_MST
 ADD CONSTRAINT ORD_MST_PK PRIMARY KEY ( ORD_NO )
 USING INDEX ORD_MST_PK;

ALTER TABLE ORD_MST
 ADD CONSTRAINT ORD_MST_FK FOREIGN KEY ( CUST_NO )
 REFERENCES CUST (CUST_NO );

desc ord_mst;

CREATE TABLE ORD_DTL
(
    ORD_NO    CHAR(10) NOT NULL,
    BK_NO    CHAR(10) NOT NULL,
    ORD_CNT    NUMBER(9) DEFAULT 0 NOT NULL,
    ORD_UPRC    NUMBER(9) DEFAULT 0 NOT NULL,
    ORD_AMT    NUMBER(9) DEFAULT 0 NOT NULL
);

COMMENT ON COLUMN ORD_DTL.ORD_NO IS '주문번호';

COMMENT ON COLUMN ORD_DTL.BK_NO IS '도서번호';

COMMENT ON COLUMN ORD_DTL.ORD_CNT IS '주문건수';

COMMENT ON COLUMN ORD_DTL.ORD_UPRC IS '주문단가';

COMMENT ON COLUMN ORD_DTL.ORD_AMT IS '주문금액';

COMMENT ON TABLE ORD_DTL IS '주문상세';

CREATE UNIQUE INDEX ORD_DTL_PK ON ORD_DTL
( BK_NO,ORD_NO );

 ALTER TABLE ORD_DTL
 ADD CONSTRAINT ORD_DTL_PK PRIMARY KEY ( BK_NO,ORD_NO )
 USING INDEX ORD_DTL_PK;

ALTER TABLE ORD_DTL
 ADD CONSTRAINT ORD_DTL_FK FOREIGN KEY ( ORD_NO )
 REFERENCES ORD_MST (ORD_NO );

ALTER TABLE ORD_DTL
 ADD CONSTRAINT ORD_DTL_FK1 FOREIGN KEY ( BK_NO )
 REFERENCES BOOK (BK_NO );

